
// import Navigation from "@/components/HeaderAdmin";
import { Inter } from "next/font/google";
import "./globals.css";
//  import 'primereact/resources/themes/saga-blue/theme.css'; // Tema de PrimeReact
//  import 'primereact/resources/primereact.min.css'; // Estilos básicos de PrimeReact
//  import 'primeicons/primeicons.css'; // Iconos de PrimeIcons

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" /> */}
        {/* <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/> */}
    
      </head>
      <body 
       className={inter.className}
      >
         {/* <Navigation />  */}
        <div>
        {children}
        </div>
        </body>
    </html>
  );
}
